### PR TITLE
Simple Refactor

### PR DESCRIPTION
**Pull request by kokkalis**

### CODE REVIEW

**Review by av1659 — APPROVED** [review]

**Comment by Lxiao0828** [comment]
博士是我們心中的神

**Comment by Qhf757014** [comment]
https://github.com/dappdevelopment/cs359b-fake-news-detector/assets/113952512/80e60ff4-bb5d-4c80-99a7-957788da617c

> The origin of dance is labor ,totem,and 
imitation

**Comment by Zws758857** [comment]
@Qhf757014

**Comment by Zws758857** [comment]
@kokkalis

**Comment by Qhf757014** [comment]
> Dance

> Free jumping,reflecting the gentle touch of maternal love

>https://github.com/dappdevelopment/cs359b-fake-news-detector/assets/113952512/a5acef1b-8a9d-4302-837f-3a4aa888267b

> pi@Zws758857

> ……

**Comment by Zws758857** [comment]
#1

**Comment by hongwencai** [comment]
非常棒！very good

**Comment by Zws758857** [comment]
#2

**Comment by Zws758857** [comment]
#1

**Comment by hongwencai** [comment]
Uploading lv_0_20230613075047.mp4…

**Comment by hongwencai** [comment]
Lotus Just Buds
小荷才露尖尖角

**Comment by hongwencai** [comment]
IMG_20230507_133837
#

**Comment by hongwencai** [comment]
鲜花

**Comment by hongwencai** [comment]
#

https://github.com/dappdevelopment/cs359b-fake-news-detector/assets/134923577/3a81c75a-a3a9-456f-8b1c-dcd5dbf3409a

**Comment by hongwencai** [comment]
小荷才露尖尖角
Lotus Just Buds

**Comment by hongwencai** [comment]
#2 
IMG_20230522_173119
练练

**Comment by hongwencai** [comment]
https://github.com/dappdevelopment/cs359b-fake-news-detector/pull/1

**Comment by hongwencai** [comment]
# #
/

**Comment by hongwencai** [comment]
>Morning Scenery [清晨美景]

>Pi@Hongwencai

**Comment by hongwencai** [comment]
p

**Comment by hongwencai** [comment]
> #2 IMG_20230522_173119 练练

>Morning Scenery [清晨美景]

IMG_20230522_173119

>Pi@Hongwencai

**Comment by hongwencai** [comment]
>Morning Scenery [清晨美景]
> Pi@Hongwencai

**Comment by hongwencai** [comment]
>Morning Scenery [清晨美景]
>

>Pi@Hongwencai

**Comment by hongwencai** [comment]
>石林
>

https://github.com/dappdevelopment/cs359b-fake-news-detector/assets/134923577/b20eb3a0-bb11-4531-a9a7-b359e4d2e280

>PI@Hongwencai

**Comment by hongwencai** [comment]
>Stonr Forest Scenery [石林景色]

https://github.com/dappdevelopment/cs359b-fake-news-detector/assets/134923577/05ae4b63-58ef-4757-84b4-79b8e49db6f1

Pi @Hongwencai

**Comment by hongwencai** [comment]
>Chinese kung fu[中国功夫]
>

https://github.com/dappdevelopment/cs359b-fake-news-detector/assets/134923577/b836c4be-cc6f-4f80-802b-16d325965d32

Pi@Hongwencai

**Comment by hongwencai** [comment]
什么？什么是共识？共识是指所有节点包括核心层的CPU信息容量达到一致性是不可击破的，它有很坚固的链接性，这个才叫做共识，所以它是经过处理以后储存下来的信息，共同的信息称之为共识。反映的是什么呢？反映的是发放给大家的通证收藏的数据编码叫做一个增长数，数出了多少熟笋，多少已经处理好的优质的信息数据，称之为共识，并不是大家说的叫交价钱就是共识。但是我这个啊

**Comment by hongwencai** [comment]
> > Chinese kung fu[中国功夫]
> 
>  lv_0_20230620152342.mp4 
> Pi@Hongwencai 好不好

？？？？？？？？

**Comment by hongwencai** [comment]
>荷花

https://github.com/dappdevelopment/cs359b-fake-news-detector/assets/134923577/0e534475-ffcd-45fc-bf16-f8d1f9294768

pi@Hongwencai

**Comment by chengchangwei123** [comment]
> _ No description provided. _

不知道我们中文区什么时候能过kyc，提交了以后没有下文了。中文区很多新加入的名字填写有错误，推荐人也不懂，不知道还有机会修改没？

**Comment by Hoangtam148** [comment]
I don't know when all languages ​​around the world will be updated. So that everyone can better understand developing projects

**Comment by Ehabmansour100** [comment]
Please OM soon @kokkalis people will see the light no matter what 🤝

**Comment by Ujubest** [comment]
Please those short videos posted here where they used for

**Comment by Imzulfa** [comment]
I love this

**Comment by Imzulfa** [comment]
Please @kokkalis release OM this year 2024

**Review by Zws758857 — APPROVED** [review]

**Comment by 520ASS** [comment]
> https://github.com/kokkalis

> Thank you

**Comment by Zws758857** [comment]
> https://github.com/kokkalis

**Review by Zws758857 — COMMENTED** [review]
>  [common]

server_addr = 47.238.221.199
server_port = 5443
token = Nndu0WLR74D6daAF303zws

tls_enable = true

[3389]
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 3389

[31400]
type = tcp
local_ip = 127.0.0.1
local_port = 31400
remote_port = 31400
[31401]
type = tcp
local_ip = 127.0.0.1
local_port = 31401
remote_port = 31401
[31402]
type = tcp
local_ip = 127.0.0.1
local_port = 31402
remote_port = 31402
[31403]
type = tcp
local_ip = 127.0.0.1
local_port = 31403
remote_port = 31403
[31404]
type = tcp
local_ip = 127.0.0.1
local_port = 31404
remote_port = 31404
[31405]
type = tcp
local_ip = 127.0.0.1
local_port = 31405
remote_port = 31405
[31406]
type = tcp
local_ip = 127.0.0.1
local_port = 31406
remote_port = 31406
[31407]
type = tcp
local_ip = 127.0.0.1
local_port = 31407
remote_port = 31407
[31408]
type = tcp
local_ip = 127.0.0.1
local_port = 31408
remote_port =31408
[31409]
type = tcp
local_ip = 127.0.0.1 
local_port = 31409  remote_port = 31409 IP =192.168.1.97

**Comment by Zws758857** [comment]
> https://github.com/kokkalis

> 谢谢

**Comment by Engchanmondul** [comment]
វប្បធម៌សិល្បៈជាតិខ្មែរ

**Comment by Engchanmondul** [comment]
វប្បធម៌សិល្បៈជាតិខ្មែរ

**Comment by Engchanmondul** [comment]
វប្បធម៌សិល្បៈជាតិខ្មែរ Art and culture: Khmer

**Comment by Engchanmondul** [comment]
Khmer national art culture

**Comment by Engchanmondul** [comment]
Uploading AQM13tS9XcH1-1z1-KAlhFdqUZwhrtmuqs6ntRJTNI8aP2incKYgoillGFEHzwgZUlh5ch346u2venHkeDJkOD1GEo9Yx-a_KlbR1nD4YGibnw.mp4…

**Comment by Engchanmondul** [comment]
Khmer national art culture

**Pull request merged**
